### ISSUE TITLE
Need to update this thing to v5 of the API

### ISSUE THREAD

**Issue by sithtoast** [WebTheoryLLC/omniauth-twitch#10]
that shouldn't be too hard, right?

**Comment by ossareh** [comment]
@sithtoast have you researched this? As I understand the code I think it's good to go:
- it doesn't specify a version, so by default gets the latest version
- it [already pulls `_id`](https://github.com/WebTheoryLLC/omniauth-twitch/blob/master/lib/omniauth/strategies/twitch.rb#L23) from the payload as the canonical id

Am I missing something?

**Comment by ossareh** [comment]
Supporting docs for "get the default if you don't ask for a version": https://github.com/justintv/Twitch-API#api-versions-and-mime-types

That said, it might be a really solid idea to explicitly request a version :)

**Comment by fx** [comment]
@ossareh HeyGuys

I'll make sure this works and update here or submit a PR :)

**Comment by jcgertig** [comment]
Yeah @ossareh I had been looking into that but had not gotten to it yet
@fx that would great
