### ISSUE TITLE
Updates for NEW twitch api on helix

### ISSUE THREAD

**Issue by jcgertig** [WebTheoryLLC/omniauth-twitch#11]
auth is not moving from kraken route but other requests are not on the url https://api.twitch.tv/helix

**Comment by jcgertig** [comment]
Nothing to do since auth routes did not change

**Comment by mauricew** [comment]
https://discuss.dev.twitch.tv/t/oauth-kraken-migration/14606

**Comment by RKushnir** [comment]
Any plans to support the new API? Re-open this issue, for the start? Twitch are deprecating the old one the end of this year.
