### ISSUE TITLE
Gemfile 

### ISSUE THREAD

**Issue by vitorguima** [WebTheoryLLC/omniauth-twitch#19]
I was having a callback problem, after my POST request to twitch, when the gem was set to:

`gem 'omniauth-twitch'`

I had to change it to:

`gem 'omniauth-twitch', git: 'git://github.com/WebTheoryLLC/omniauth-twitch.git'`

It was the only change that I did in my code and it worked fine. Also, I saw some unsolved threads with this same issue around the internet. My suggestion is: change it in the Readme file.

**Comment by elliotcm** [comment]
It looks like this change was merged but not released as a new gem version:
https://github.com/WebTheoryLLC/omniauth-twitch/commit/500027926f44362daefa1818aa58080b456199c9

So a 1.1.1 release would be the right move.

cc @sithtoast

**Comment by elliotcm** [comment]
@vitorguima Since it doesn't look like this gem is getting a new release any time soon, I've released these changes under the name `omniauth-twitch_smartcasual`, version 1.1.1.

**Comment by deanpcmad** [comment]
This is now fixed with v1.2.0
